services:
  api:
    build: .
    ports:
      - "6543:8080"
    environment:
      ENVIRONMENT: development
      DATABASE_URL: postgresql://postgres:password@db:5432/python-server-demo
    depends_on:
      - migration
  migration:
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/python-server-demo
    entrypoint: [ 'flask', 'db', 'upgrade' ]
    depends_on:
      - db
  db:
    image: postgres:17
    ports:
      - '5432:5432'
    container_name: demo-db
    restart: always
    environment:
      POSTGRES_DB: python-server-demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
