name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
    - uses: actions/setup-python@v3
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV  # Add src to PYTHONPATH
    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt --system
    - name: UT
      run: |
        pytest
    - name: pre-commit for pre-commit
      uses: pre-commit/action@v3.0.1
