name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv pip install -r requirements.txt
    - name: Install pytest globally
      run: |
        pip install pytest
    - name: pre-commit for pre-commit
      uses: pre-commit/action@v3.0.1
      with:
        python: .venv/bin/python
    - name: pre-commit for pre-push
      uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files --hook-stage pre-push
        python: .venv/bin/python
